#!/usr/bin/env python3
"""Convert an audio file into an embeddable Cheeko PCM header.

Resamples to mono 16-bit at the device sample rate (16 kHz) via ffmpeg,
applies a short fade-out (abruptly ending PCM clicks audibly — SKILL.md
section 6), and emits a const int16_t array for Speaker::PlayPcm().

Budget: 32 KB of flash per second of audio. Keep clips under ~5 seconds.

Usage:
  python tools/audio2cheeko.py in.wav out.h --name boot_voice
"""
import argparse
import struct
import subprocess
from pathlib import Path


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("input")
    parser.add_argument("output")
    parser.add_argument("--name", required=True, help="C identifier stem")
    parser.add_argument("--rate", type=int, default=16000)
    parser.add_argument("--fade", type=float, default=0.2, help="fade-out seconds")
    parser.add_argument("--max-seconds", type=float, default=6.0)
    args = parser.parse_args()

    probe = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration",
         "-of", "default=noprint_wrappers=1:nokey=1", args.input],
        capture_output=True, text=True, check=True)
    duration = min(float(probe.stdout.strip()), args.max_seconds)
    fade_start = max(0.0, duration - args.fade)

    raw = subprocess.run(
        ["ffmpeg", "-v", "error", "-i", args.input, "-t", str(duration),
         "-ac", "1", "-ar", str(args.rate),
         "-af", f"afade=t=out:st={fade_start:.3f}:d={args.fade:.3f}",
         "-f", "s16le", "-acodec", "pcm_s16le", "pipe:1"],
        capture_output=True, check=True).stdout

    samples = struct.unpack(f"<{len(raw) // 2}h", raw)
    name = args.name
    guard = name.upper()
    lines = [
        "#pragma once",
        "",
        f"// Generated by tools/audio2cheeko.py from {Path(args.input).name}",
        f"// {len(samples)} samples, {args.rate} Hz mono, {duration:.2f}s, "
        f"~{len(samples) * 2 // 1024} KB of flash.",
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        f"constexpr int k{guard}_RATE = {args.rate};",
        f"constexpr size_t k{guard}_LEN = {len(samples)};",
        f"const int16_t k{guard}_PCM[] = {{",
    ]
    for i in range(0, len(samples), 16):
        chunk = ", ".join(str(s) for s in samples[i:i + 16])
        lines.append(f"    {chunk},")
    lines.append("};")
    Path(args.output).write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{args.output}: {len(samples)} samples @ {args.rate} Hz "
          f"({duration:.2f}s, ~{len(samples) * 2 // 1024} KB)")


if __name__ == "__main__":
    main()
