#!/usr/bin/env python3
"""Convert an image into an embeddable Cheeko drawing header.

The output is a C++ header with a small color palette and horizontal
run-length spans, drawn through the public SDK (one FillRect per run) so it
works identically in the simulator and on the device, where long spans are
the fast path over SPI.

Usage:
  python tools/img2cheeko.py input.png output.h --name mask --width 200
  # then in an app:  #include "output.h"   DrawMask(Cheeko().display(), x, y);

Background pixels (sampled from the image corners, or --background RRGGBB)
are skipped entirely, so the app's own background shows through.
"""
import argparse
from pathlib import Path

from PIL import Image


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("input")
    parser.add_argument("output")
    parser.add_argument("--name", required=True, help="C identifier stem, e.g. mask")
    parser.add_argument("--width", type=int, default=200)
    parser.add_argument("--colors", type=int, default=8)
    parser.add_argument("--background", help="hex color to treat as transparent (default: corner sample)")
    parser.add_argument("--fill-holes",
                        help="hex color for ENCLOSED transparent regions (e.g. logo eye "
                             "cutouts); outer transparency still shows the app background")
    args = parser.parse_args()

    img = Image.open(args.input).convert("RGBA")
    height = max(1, round(args.width * img.height / img.width))
    img = img.resize((args.width, height), Image.LANCZOS)

    # Flatten transparency onto a sentinel color so real image colors (e.g. a
    # white that matches a white page background) are never dropped. The
    # alpha channel is binarized so antialiased edges don't tint the sentinel.
    corners = [img.getpixel(p) for p in
               [(0, 0), (img.width - 1, 0), (0, img.height - 1),
                (img.width - 1, img.height - 1)]]
    has_alpha = any(c[3] < 128 for c in corners)
    if args.background:
        bg = tuple(int(args.background[i:i + 2], 16) for i in (0, 2, 4))
    elif has_alpha:
        bg = (255, 0, 255)  # magenta sentinel: never a real logo color
    else:
        opaque = [c[:3] for c in corners if c[3] > 128]
        bg = opaque[0] if opaque else (255, 255, 255)
    alpha = img.split()[3].point(lambda a: 255 if a > 128 else 0)

    if args.fill_holes:
        # Flood-fill transparency from the border; whatever transparent area
        # the flood cannot reach is enclosed (an eye cutout) and gets painted.
        hole_rgb = tuple(int(args.fill_holes[i:i + 2], 16) for i in (0, 2, 4))
        a = alpha.load()
        w, h = img.size
        outside = [[False] * h for _ in range(w)]
        stack = [(x, y) for x in range(w) for y in (0, h - 1) if a[x, y] == 0]
        stack += [(x, y) for y in range(h) for x in (0, w - 1) if a[x, y] == 0]
        while stack:
            x, y = stack.pop()
            if x < 0 or y < 0 or x >= w or y >= h or outside[x][y] or a[x, y] != 0:
                continue
            outside[x][y] = True
            stack += [(x + 1, y), (x - 1, y), (x, y + 1), (x, y - 1)]
        px = img.load()
        for x in range(w):
            for y in range(h):
                if a[x, y] == 0 and not outside[x][y]:
                    px[x, y] = hole_rgb + (255,)
                    a[x, y] = 255

    flat = Image.new("RGB", img.size, bg)
    flat.paste(img, mask=alpha)

    quant = flat.quantize(colors=args.colors, dither=Image.Dither.NONE)
    palette = quant.getpalette()
    pixels = quant.load()

    def color_of(index):
        return tuple(palette[index * 3:index * 3 + 3])

    def is_background(rgb):
        return all(abs(rgb[i] - bg[i]) < 28 for i in range(3))

    used = {}
    runs = []  # (y, x, length, palette_slot)
    for y in range(quant.height):
        x = 0
        while x < quant.width:
            idx = pixels[x, y]
            rgb = color_of(idx)
            if is_background(rgb):
                x += 1
                continue
            start = x
            while x < quant.width and pixels[x, y] == idx:
                x += 1
            slot = used.setdefault(rgb, len(used))
            runs.append((y, start, x - start, slot))

    name = args.name
    guard = name.upper()
    lines = [
        "#pragma once",
        "",
        f"// Generated by tools/img2cheeko.py from {Path(args.input).name}",
        f"// {quant.width}x{quant.height}, {len(used)} colors, {len(runs)} runs.",
        "",
        "#include <cstdint>",
        "",
        '#include "cheeko.h"',
        "",
        f"constexpr int k{guard}_W = {quant.width};",
        f"constexpr int k{guard}_H = {quant.height};",
        f"constexpr int k{guard}_RUNS = {len(runs)};",
        "",
        f"const uint32_t k{guard}_PALETTE[] = {{",
    ]
    for rgb, slot in sorted(used.items(), key=lambda kv: kv[1]):
        lines.append(f"    0x{rgb[0]:02x}{rgb[1]:02x}{rgb[2]:02x},")
    lines.append("};")
    lines.append("")
    lines.append(f"// y, x, length, palette index")
    lines.append(f"const uint16_t k{guard}_RUN_DATA[][4] = {{")
    for y, x, length, slot in runs:
        lines.append(f"    {{{y}, {x}, {length}, {slot}}},")
    lines.append("};")
    lines.append("")
    lines.append(
        f"inline void Draw{name.title().replace('_', '')}(cheeko::Display& d, int ox, int oy) {{\n"
        f"  for (int i = 0; i < k{guard}_RUNS; ++i) {{\n"
        f"    const uint16_t* r = k{guard}_RUN_DATA[i];\n"
        f"    d.FillRect(ox + r[1], oy + r[0], r[2], 1, k{guard}_PALETTE[r[3]]);\n"
        f"  }}\n"
        f"}}")
    Path(args.output).write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{args.output}: {quant.width}x{quant.height}, {len(used)} colors, "
          f"{len(runs)} runs (~{len(runs) * 8 // 1024} KB)")


if __name__ == "__main__":
    main()
